buildscript {
    configurations.classpath.resolutionStrategy.force('com.google.code.gson:gson:2.10.1')
    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
    }
    dependencies {
        classpath 'com.google.code.gson:gson:2.10.1'
        classpath 'net.fabricmc:fabric-loom:1.8.13'
    }
}

plugins {
    id 'eclipse'
    id 'maven-publish'
}
apply plugin: 'fabric-loom'
apply plugin: 'java'

version = "${mod_version}" + (System.getenv('BUILD_NUMBER') ?: '0')
group = mod_group
archivesBaseName = "${mod_name}-${version_minecraft}"

base {
    archivesName = "${mod_name}-${version_minecraft}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            runDir("run")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${version_minecraft}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
